### ISSUE TITLE
Cant add TV SHows

### ISSUE THREAD

**Issue by mitral** [ilucas/TVShows#6]
Been having this trouble with this app. When I double cick the plus button on the latest version. I dont get a an option to add tv shows and such.. What do I do/am i doing wrong?

**Comment by ilucas** [comment]
When you click on  "add tv shows" do you see this window?
![screen shot 2016-08-06 at 1 58 53 pm](https://cloud.githubusercontent.com/assets/896931/17458059/eed342fc-5bdd-11e6-808d-9193788ca5b3.png)

**Comment by mitral** [comment]
@ilucas I do. What would I do next?

**Comment by ilucas** [comment]
![addshow](https://cloud.githubusercontent.com/assets/896931/17458572/878c1d18-5beb-11e6-9392-97bc6a985fc5.gif)

**Comment by mitral** [comment]
@ilucas Got it THanks!>

**Comment by mitral** [comment]
@ilucas the shows are saved in Downlaods folder by default right? after they are done downloading or?

**Comment by mitral** [comment]
@ilucas actaully I figured it out. Thanks again. Ill try to let you knw of more issues
