### ISSUE TITLE
Question about the app

### ISSUE THREAD

**Issue by mitral** [ilucas/TVShows#7]
Hi,
I'm just wondering vs the older TV shows and this new one. How does this one get the airdates for the next episode of the TV show. Like for example, some shows like "Quantico" dont start till the fall.

**Comment by ilucas** [comment]
All the data about the shows, including air date, is provided by [TheTVDB](http://www.thetvdb.com).

**Comment by mitral** [comment]
@ilucas I see. Thanks same as old one then. Glad to know it hasn't changed
